---
db:
  type: mysql
  host: localhost
  name: opar
  user: opar
  pass: hot
paths:
  base: /home/opar/opar_sources/
  templates: templates/
  conf: /home/opar/opar_sources/conf/
  static: static/
  mails: mails/
  uploads: /home/opar/uploads/
defaults:
  static: imprint
templates:
  base: opar.tmpl
  author: opar.tmpl
logging: logging.web.conf
formid:
  expire: 200
time:
  deletion: 259200
mail:
  smtp: mail.perl-services.de
  user: opar@perl-services.de
  pass: 391TWgb!
  from: opar@perl-services.de
  to: reb@perl-services.de
  subject: Mail von OPAR
password:
  salt: OPAR
admin:
  startpage: menu
utils:
  perltidy:
    config: perltidyrc
  perlcritic:
    config: perlcriticrc
general:
  perl_version: 5.008001
