---
db:
  type: mysql
  host: localhost
  name: opar
  user: opar
  pass: hot
paths:
  base: /home/opar/opar_sources/
  templates: templates/
  conf: /home/opar/opar_sources/conf/
templates:
  base: main.tmpl
logging: logging.web.conf
password:
  salt: OPAR
admin:
  startpage: menu
utils:
  perltidy:
    config: perltidyrc
  perlcritic:
    config: perlcriticrc
general:
  perl_version: 5.008001
